import type { GalleryItem } from '@/types';

export const GALLERY_ITEMS: GalleryItem[] = [
  // ── Yemekler ──────────────────────────────────────────
  {
    id: '1',
    src: '/images/menu/kuzu-kavurma.jpg',
    alt: 'Dana kavurma servis',
    category: 'food',
    width: 1535,
    height: 1920,
  },
  {
    id: '2',
    src: '/images/menu/tavuk.jpg',
    alt: 'Tavuk kavurma',
    category: 'food',
    width: 1535,
    height: 1920,
  },
  {
    id: '3',
    src: '/images/menu/kavurma-ekmek-arasi.jpg',
    alt: 'Kavurma ekmek arası',
    category: 'food',
    width: 1536,
    height: 1920,
  },
  {
    id: '4',
    src: '/images/menu/mercimek-corbasi.jpg',
    alt: 'Mercimek çorbası',
    category: 'food',
    width: 1536,
    height: 1920,
  },
  {
    id: '5',
    src: '/images/menu/ezogelin-corbasi.jpg',
    alt: 'Ezogelin çorbası',
    category: 'food',
    width: 1536,
    height: 1920,
  },
  {
    id: '6',
    src: '/images/gallery/masa-kavurma-servis.jpg',
    alt: 'Masada kavurma servisi',
    category: 'food',
    width: 1279,
    height: 1920,
  },
  {
    id: '7',
    src: '/images/gallery/kavurma-ayran-servis.jpg',
    alt: 'Kavurma ve ayran',
    category: 'food',
    width: 1279,
    height: 1920,
  },
  {
    id: '8',
    src: '/images/gallery/misafir-sandvic.jpg',
    alt: 'Kavurma ekmek arası - misafir',
    category: 'food',
    width: 1536,
    height: 1920,
  },
  {
    id: '9',
    src: '/images/gallery/misafir-gulerken.jpg',
    alt: 'Mutlu misafir - kavurma',
    category: 'food',
    width: 1536,
    height: 1920,
  },

  // ── Mekan / Mutfak ────────────────────────────────────
  {
    id: '10',
    src: '/images/gallery/buyuk-tepsi-kavurma.jpg',
    alt: 'Geleneksel bakır tepside kavurma',
    category: 'venue',
    width: 1536,
    height: 1920,
  },
  {
    id: '11',
    src: '/images/gallery/kavurma-bakir-kepce.jpg',
    alt: 'Bakır kepçeyle kavurma alma',
    category: 'venue',
    width: 1536,
    height: 1920,
  },
  {
    id: '12',
    src: '/images/gallery/kavurma-yufka-hazirlik.jpg',
    alt: 'Yufka üzerinde kavurma hazırlığı',
    category: 'venue',
    width: 1536,
    height: 1920,
  },
  {
    id: '13',
    src: '/images/mehmet-usta-isbasi.jpg',
    alt: 'Mehmet Usta işbaşında',
    category: 'venue',
    width: 1535,
    height: 1920,
  },
  {
    id: '14',
    src: '/images/ilik-kemikleri.jpg',
    alt: 'İlik kemikleri pişirme',
    category: 'venue',
    width: 1536,
    height: 1920,
  },
];
